### ISSUE TITLE
Add an excludedFields BasicCardRequest parameter

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/webpayments-methods-card#29] opened 2017-04-03 20:04 UTC
I am starting this new issue based on previous comments from @mattsaxon in issue #26 and issue #5, and inspired by his previous proposal:
  https://github.com/w3c/browser-payment-api/issues/143#issuecomment-215738721

Here's a proposal:

 * Add a field for BasicCardRequest: "excludedFields". This list is the merchant preference for the user agent NOT returning a those fields in the BasicCardResponse.
 * At least for version 1, user agents SHOULD NOT return the excludedField in the BasicCardResponse.
 * Any excludedFields values that do not correspond to field names in section 5.1 of the spec are ignored by user agents.

I'd like to hear from implementers.

**Comment by mattsaxon** [comment] 2017-04-04 06:34
+1

**Comment by marcoscaceres** [comment] 2017-04-04 06:38
Reminder, to +1 use the GH provided buttons for reactions:
 
![screenshot 2017-04-04 16 36 37](https://cloud.githubusercontent.com/assets/870154/24644068/fec9730e-1954-11e7-927c-47f02cdb81c9.png)

(Marcos deletes all "+1" comments from the issue tracker)

**Comment by zkoch** [comment] 2017-04-19 22:32
I think there is value in this, but given that we already have two implementations out in the wild that rely on this spec, I don't think now is the appropriate time to add. I would propose that we consider this for the next version after we get to CR.

**Comment by mattsaxon** [comment] 2017-04-20 14:18
Happy for it to be postponed, but let's not close.

**Comment by marcoscaceres** [comment] 2017-09-20 07:29
Now might be a good time to return to this. From the members of `BasicCardResponse`, what's the use case for the merchant excluding any of the members?

**Comment by rsolomakhin** [comment] 2017-09-20 10:30
@marcoscaceres The use case is some merchants that don't require CVC or billing address to charge your card. Some merchants make this tradeoff to increase conversions at the cost of higher fraud risk.

**Comment by ianbjacobs** [comment] 2017-09-20 12:59
@mattsaxon, do you want to weigh in as well now that we are returning to this?

Ian

**Comment by marcoscaceres** [comment] 2017-09-20 13:07
@rsolomakhin, I see. The problem now is that shipping implementations will return all the values (even if we added support for this tomorrow). 

Why couldn't a merchant just pretend the values are not there in the response and simply not use them?

**Comment by ianbjacobs** [comment] 2017-09-20 13:14
Hi @marcoscaceres,

The merchant wants to say to the browser: "I don't want this, so please don't show UI to the user because that will reduce the chances the transaction will be completed." Right now merchants
can't say that.

Ian

**Comment by rsolomakhin** [comment] 2017-09-20 13:35
Personally I'm against giving too many options to the merchant in this case, because I don't want PaymentRequest to become a glorified form builder. If there's demand for such customization, custom payment methods should provide it, e.g., "https://credit-cards.com/no-cvc-or-billing-address".

**Comment by marcoscaceres** [comment] 2017-09-20 14:06
I agree with @rsolomakhin. Remember that the Payment Sheet is not a form for the merchant... it's  kinda like a "wallet", where users can see all their cards, make modifications/updates to those cards (even if the cards shown have been filtered by type), etc. so it might become confusing if we start arbitrarily taking away things that users expect to be there.

**Comment by marcoscaceres** [comment] 2017-09-20 14:15
Just one more point: the assumption should really be that the user has already filled out the information in the basic card storage... there is a good chance of that, specially as time goes on (because the  autofill DB will likely have this information) and because the chances of the user previously having used the API on some other site goes up over time. 

Thus, the notion of "that will reduce the chances the transaction will be completed" becomes irrelevant and not a concern. In fact, we actually really want users to add as much info as possible, as they only have to do it once and then the whole ecosystem benefits as a result.

**Comment by marcoscaceres** [comment] 2018-11-21 05:49
Closing as duplicate of #5.

**Closed as completed by marcoscaceres** 2018-11-21 05:49 UTC
Labels: Priority: Postponed
